### ISSUE TITLE
Bug: StatusException: UNAVAILABLE: End of stream or IOException - the library function should throw exception so we can handle that in our code and do the appropriate action for that

### ISSUE THREAD

**Issue by rsappelit** [xmtp/xmtp-android#233]
### Describe the bug

**Point 1:** We have used this code to get the streamMessages of converstations

````
var client = XMTPManager.fetchClient()
            if (client == null) {
                viewModelScope.launch {
                    XMTPManager.setupXMTP {
                        client = XMTPManager.fetchClient()
                        Unit
                    }
                }
            }
            client
                ?.conversations
                ?.streamAllMessages()
                ?.flowWhileShared(
                    subscriptionCount, SharingStarted.WhileSubscribed(1000L)
                )
                ?.flowOn(Dispatchers.IO)
                ?.distinctUntilChanged()
                ?.mapLatest { conversation ->
                    XMTPManager.parseMessage(conversation)
//                    throw Exception("Test Crash")
                }
                ?.catch {
                    Logger.e(TAG, it.message, it)
                    emptyFlow<MessageInfo>()
                } ?: emptyFlow<MessageInfo>()
````

**Point 2 :** If Conversation screen is Active for 15 to 20 minutes then this crash happens

````
FATAL EXCEPTION: DefaultDispatcher-worker-5
                 Process: com.qriptos.app.dev, PID: 26058
                 io.grpc.StatusException: UNAVAILABLE: End of stream or IOException
                 	at io.grpc.Status.asException(Status.java:548)
                 	at io.grpc.kotlin.ClientCalls$rpcImpl$1$1$1.onClose(ClientCalls.kt:300)
                 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574)
                 	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72)
                 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
                 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
                 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
                 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                 	at java.lang.Thread.run(Thread.java:784)
````

### Expected behavior

Whenever any crash happens in the library function than throw the exception. So we can handle that exception in our project code and perform the appropriate action according to that.

### Steps to reproduce the bug

1. Open the Conversation listing Screen
2. Stay there for 15 to 20 minutes
3. And App will be crashed

**Comment by bwcDvorak** [comment]
Thanks for reporting this! Can we ask what version of the SDK you're testing on when this happens?

**Comment by rsappelit** [comment]
Version : 0.10.5
Date : 19-Apri-24
Tested on these devices Device : Google Pixel 5 , Y7 Prime 2019

**Comment by nplasterer** [comment]
I'm hoping that these streaming crashes should get fixed with this backend update. https://github.com/xmtp/xmtp-node-go/pull/388#pullrequestreview-2036936196 I'll still work to surface the error so it's easier to catch and not crash.

**Comment by nplasterer** [comment]
Latest Android release should no longer have these issues. 🙏
