### ISSUE TITLE
Bug: uniffi.xmtpv3.GenericException$Client: Client error: storage error

### ISSUE THREAD

**Issue by guangxingmao** [xmtp/xmtp-android#319]
### Describe the bug

`val inboxId = ClientManager.client.v3Client?.findInboxId("0x9D2a9DdbfA9D164c2ADB1bE54f322e239571c803")
inboxId = "6a9388a671c4bf240b925a54ba13926ec5b8d86420a1cc98ae731975ab0ab518"`

 FindInboxId, It's ok.

`ClientManager.client.v3Client?.dmConversation(inboxId)`

DmConversation,It's error

` uniffi.xmtpv3.GenericException$Client: Client error: storage error: dm_target_inbox_id 36613933383861363731633462663234306239323561353462613133393236656335623864383634323061316363393861653733313937356162306162353138 not found
                                                                                                    	at uniffi.xmtpv3.FfiConverterTypeGenericError.read(xmtpv3.kt:9230)
                                                                                                    	at uniffi.xmtpv3.FfiConverterTypeGenericError.read(xmtpv3.kt:9226)
                                                                                                    	at uniffi.xmtpv3.FfiConverter$DefaultImpls.liftFromRustBuffer(xmtpv3.kt:208)
                                                                                                    	at uniffi.xmtpv3.FfiConverterRustBuffer$DefaultImpls.liftFromRustBuffer(xmtpv3.kt:224)
                                                                                                    	at uniffi.xmtpv3.FfiConverterTypeGenericError.liftFromRustBuffer(xmtpv3.kt:9226)
                                                                                                    	at uniffi.xmtpv3.FfiConverterTypeGenericError.liftFromRustBuffer(xmtpv3.kt:9226)
                                                                                                    	at uniffi.xmtpv3.FfiConverterRustBuffer$DefaultImpls.lift(xmtpv3.kt:225)
                                                                                                    	at uniffi.xmtpv3.FfiConverterTypeGenericError.lift(xmtpv3.kt:9226)
                                                                                                    	at uniffi.xmtpv3.FfiConverterTypeGenericError.lift(xmtpv3.kt:9226)
                                                                                                    	at uniffi.xmtpv3.GenericException$ErrorHandler.lift(xmtpv3.kt:9219)
                                                                                                    	at uniffi.xmtpv3.GenericException$ErrorHandler.lift(xmtpv3.kt:9217)
                                                                                                    	at uniffi.xmtpv3.Xmtpv3Kt.uniffiCheckCallStatus(xmtpv3.kt:300)
                                                                                                    	at uniffi.xmtpv3.Xmtpv3Kt.access$uniffiCheckCallStatus(xmtpv3.kt:1)
                                                                                                    	at uniffi.xmtpv3.FfiXmtpClient.dmConversation(xmtpv3.kt:10716)
                                                                                                    	at org.xmtp.android.example.MainActivity$onCreate$2$1.invokeSuspend(MainActivity.kt:81)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:908)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                                                    	at android.os.Looper.loop(Looper.java:219)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8679)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@50b60a6, Dispatchers.Main.immediate]`

**Comment by nplasterer** [comment]
@guangxingmao I would caution calling libxmtp methods directly from android. You should instead be using the sdk functionality I have exposed `ClientManager.client.findDm(address)` This finds the DM from the address. I can expose one that finds it by inboxId as well if that would be helpful but I would not call methods directly on the v3Client. The ability to do that will be going away in v3.0.0.
